# Generated by Django 2.0.13 on 2020-02-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagories',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(max_length=120),
        ),
    ]
