# Generated by Django 2.0.13 on 2020-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200211_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagories',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
